language: python
python:
- 3.5-dev
sudo: required
services:
  - docker
cache:
  directories:
  - eggs
before_install:
- docker-compose up -d
install:
- python bootstrap-buildout.py --setuptools-version=32.1.0
- bin/buildout -t 3
- pip install flake8
- pip install coverage==4.0.3
- sleep 15
- docker-compose logs
script:
- bin/py.test -s --cov=pserver.elasticsearch -v --cov-report term-missing pserver 
- bin/code-analysis
after_success:
- coveralls
- cat .coverage
after_script:
- docker-compose stop
- docker-compose rm -f
